let IPC_Q = {
  SERVER_1: "SERVER_1_LISTENER",
  SERVER_2: "SERVER_2_LISTENER"
}

let HASH_MAPS = {
  SERVER_MAP: "SERVER_MAP"
}

const POP_TIMEOUT = 2000;

const TRANSACTION_NUMBER_THRESH = 9999999999;

const RESP_TIMEOUT_THRES = 5000;


module.exports = {
  IPC_Q,
  HASH_MAPS,
  POP_TIMEOUT,
  TRANSACTION_NUMBER_THRESH
}
